spring:
  profiles:
    active: staging
  mail:
    host: smtp.gmail.com
    port: 587
    username: hardik.khurana@octalsoftware.com
    password: sjnh jrrq mzvt fgyl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
sender.name: FSM Support