package com.octal.fsm.specification;

public enum SearchOperation {
    EQUALITY, NOT_EQUALITY, NEGATION, GREATER_THAN, LESS_THAN, LIKE, STARTS_WITH, IN, LESS_THAN_OR_EQUALS, GREATER_THAN_OR_EQUALS, INNER_JOIN

}
